# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_popgen_tools_rcpp_hello_world`)
}

a1f <- function(N) {
    .Call(`_popgen_tools_a1f`, N)
}

a2f <- function(N) {
    .Call(`_popgen_tools_a2f`, N)
}

b1f <- function(N) {
    .Call(`_popgen_tools_b1f`, N)
}

b2f <- function(N) {
    .Call(`_popgen_tools_b2f`, N)
}

c1f <- function(b1, a1) {
    .Call(`_popgen_tools_c1f`, b1, a1)
}

c2f <- function(a1, a2, b2, N) {
    .Call(`_popgen_tools_c2f`, a1, a2, b2, N)
}

e1f <- function(c1, a1) {
    .Call(`_popgen_tools_e1f`, c1, a1)
}

e2f <- function(a1, a2, c2) {
    .Call(`_popgen_tools_e2f`, a1, a2, c2)
}

theta_t <- function(G) {
    .Call(`_popgen_tools_theta_t`, G)
}

theta_w <- function(G) {
    .Call(`_popgen_tools_theta_w`, G)
}

#' taj_D function
#' @param G: A binary matrix of 0's and 1's. Each column is a SNP and each row is a sampled individual.
#' @return a scalar value of tajima's D for the sampled population. 
#' @examples taj_D(G)
#' @export
taj_D <- function(G) {
    .Call(`_popgen_tools_taj_D`, G)
}

